# Generated by Django 5.2.4 on 2025-07-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('photo', 'Фото'), ('video', 'Видео')], max_length=10, verbose_name='Тип контента')),
                ('url', models.CharField(max_length=255, verbose_name='Ссылка на медиаконтент')),
            ],
        ),
    ]
