# Generated by Django 5.2.4 on 2025-07-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0002_mainpagemedia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpagemedia',
            options={'verbose_name': 'Медиа контент для главной', 'verbose_name_plural': 'Медиа контент для главной'},
        ),
        migrations.AlterField(
            model_name='mainpagemedia',
            name='type',
            field=models.CharField(choices=[('image', 'Фото'), ('video', 'Видео')], max_length=10, verbose_name='Тип контента'),
        ),
    ]
