# Generated by Django 5.2.4 on 2025-07-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0003_alter_mainpagemedia_options_alter_mainpagemedia_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagemedia',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на превью видео'),
        ),
    ]
