# Generated by Django 5.2.4 on 2025-07-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0004_mainpagemedia_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='bg_image',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
