# Generated by Django 5.2.4 on 2025-07-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0005_pricing_bg_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='bg_image',
        ),
        migrations.AddField(
            model_name='pricing',
            name='bg_color',
            field=models.CharField(choices=[('#ebebeb', 'Серый'), ('#1c1c29', 'Черный'), ('#dcebbb', 'Салатовый')], default='#ebebeb', max_length=10, verbose_name='Цвет карточки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricing',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Описание тарифного плана'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='Доступность'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярность'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='plan',
            field=models.CharField(choices=[('zooID', 'Зоо ID'), ('concierge', 'Зооконсьерж'), ('zoopolis', 'Зоополис')], max_length=10, verbose_name='Название тарифного плана'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='price',
            field=models.IntegerField(verbose_name='Стоимость тарифного плана / месяц'),
        ),
    ]
