# Generated by Django 5.2.5 on 2025-08-18 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0006_remove_pricing_bg_image_pricing_bg_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageURL', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фото питомца')),
                ('name', models.CharField(max_length=255, verbose_name='Кличка')),
                ('type', models.CharField(choices=[('dog', 'Собака'), ('cat', 'Кошка')], max_length=10, verbose_name='Тип питомца')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, verbose_name='Пол')),
                ('breed', models.CharField(max_length=255, verbose_name='Порода')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет')),
                ('comment', models.TextField(blank=True, max_length=255, null=True, verbose_name='Комментарий')),
                ('allergies', models.TextField(blank=True, max_length=255, null=True, verbose_name='Аллергии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Питомец',
                'verbose_name_plural': 'Питомцы',
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='Код')),
                ('imageURL', models.CharField(max_length=255, verbose_name='Фото QR кода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitemanagement.pet', verbose_name='Питомец')),
            ],
            options={
                'verbose_name': 'QR код',
                'verbose_name_plural': 'QR коды',
            },
        ),
    ]
