# Generated by Django 5.2.5 on 2025-08-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0007_pet_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_lost',
            field=models.BooleanField(default=False, verbose_name='Питомец потерян?'),
        ),
    ]
