# Generated by Django 5.2.5 on 2025-08-19 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_petscolors_petstypes_petsbreeds'),
        ('sitemanagement', '0008_pet_is_lost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionaries.petsbreeds', verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionaries.petscolors', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionaries.petstypes', verbose_name='Тип питомца'),
        ),
    ]
