# Generated by Django 5.2.6 on 2025-09-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0009_alter_pet_breed_alter_pet_color_alter_pet_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='Координаты локации')),
                ('title', models.CharField(max_length=255, verbose_name='Название локации')),
            ],
            options={
                'verbose_name': 'Маркер на карте',
                'verbose_name_plural': 'Маркеры на карте',
            },
        ),
    ]
