# Generated by Django 5.2.6 on 2025-09-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0010_mappoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappoints',
            name='category',
            field=models.CharField(choices=[('clinic', 'Ветклиника'), ('pharmacy', 'Ветаптека'), ('salon', 'Зоосалон')], default='clinic', max_length=20, verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
