# Generated by Django 5.2.6 on 2025-09-05 13:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0011_mappoints_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название услуги')),
                ('description', models.CharField(max_length=100, verbose_name='Описание услуги')),
                ('imageURL', models.CharField(max_length=255, verbose_name='Ссылка на картинку')),
                ('actual_before', models.DateField(verbose_name='Действует до')),
                ('available_for', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('zooID', 'Зоо ID'), ('concierge', 'Зооконсьерж'), ('zoopolis', 'Зоополис')], max_length=20), blank=True, default=list, help_text='Выберите тарифные планы, для которых доступна услуга', null=True, size=None, verbose_name='Доступно для тарифов')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
