# Generated by Django 5.2.6 on 2025-09-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0013_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название бонуса')),
                ('description', models.TextField(max_length=255, verbose_name='Описание бонуса')),
                ('imageURL', models.CharField(max_length=255, verbose_name='Ссылка на картинку')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Бонус',
                'verbose_name_plural': 'Бонусы',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['id'], 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
    ]
