# Generated by Django 5.2.6 on 2025-09-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0014_bonuses_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuses',
            name='imageURL',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на картинку'),
        ),
    ]
