# Generated by Django 5.2.6 on 2025-09-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0015_alter_bonuses_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonuses',
            name='category',
            field=models.CharField(choices=[('discount', 'Скидки'), ('promo', 'Промокоды'), ('promotion', 'Акции')], default='discount', max_length=255, verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
