# Generated by Django 5.2.6 on 2025-09-08 08:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0016_bonuses_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonuses',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата окончания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bonuses',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала'),
            preserve_default=False,
        ),
    ]
