# Generated by Django 5.2.6 on 2025-09-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0017_bonuses_end_date_bonuses_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonuses',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Промокод'),
        ),
        migrations.AddField(
            model_name='bonuses',
            name='is_applied',
            field=models.BooleanField(default=False, verbose_name='Статус применения'),
        ),
    ]
