# Generated by Django 5.2.6 on 2025-09-08 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0018_add_bonus_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonuses',
            name='is_applied',
        ),
        migrations.CreateModel(
            name='BonusApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата применения')),
                ('bonus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitemanagement.bonuses', verbose_name='Бонус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Применение бонуса',
                'verbose_name_plural': 'Применения бонусов',
                'unique_together': {('user', 'bonus')},
            },
        ),
        migrations.AddField(
            model_name='bonuses',
            name='applied_by',
            field=models.ManyToManyField(related_name='applied_bonuses', through='sitemanagement.BonusApplication', to=settings.AUTH_USER_MODEL, verbose_name='Использован пользователями'),
        ),
    ]
