# Generated by Django 5.2.6 on 2025-09-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0019_remove_bonuses_is_applied_bonusapplication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступность услуги'),
        ),
    ]
