# Generated by Django 5.2.6 on 2025-09-09 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0020_services_is_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['id'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.RenameField(
            model_name='bonuses',
            old_name='is_active',
            new_name='is_available',
        ),
    ]
