# Generated by Django 5.2.6 on 2025-09-09 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0021_alter_services_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['id'], 'verbose_name': 'Питомец', 'verbose_name_plural': 'Питомцы'},
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='sitemanagement.pet', verbose_name='Питомец'),
        ),
    ]
