# Generated by Django 5.2.6 on 2025-09-10 08:06

import sitemanagement.constants.qr_code_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0022_alter_pet_options_alter_qrcode_pet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['-id'], 'verbose_name': 'Питомец', 'verbose_name_plural': 'Питомцы'},
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='imageURL',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=sitemanagement.constants.qr_code_path.pet_qr_upload_path, verbose_name='Фото QR кода'),
        ),
    ]
