# Generated by Django 5.2.6 on 2025-09-10 08:19

import sitemanagement.constants.pet_image_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0023_alter_pet_options_remove_qrcode_imageurl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='imageURL',
        ),
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=sitemanagement.constants.pet_image_path.pet_image_upload_path, verbose_name='Фото питомца'),
        ),
    ]
