# Generated by Django 5.2.6 on 2025-09-10 08:35

import sitemanagement.constants.image_save_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0024_remove_pet_imageurl_pet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='image',
            field=models.ImageField(upload_to=sitemanagement.constants.image_save_path.pet_qr_upload_path, verbose_name='Фото QR кода'),
        ),
    ]
