# Generated by Django 5.2.6 on 2025-09-11 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0026_tranasctions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricing',
            options={'ordering': ['id'], 'verbose_name': 'Тарифный план', 'verbose_name_plural': 'Тарифные планы'},
        ),
    ]
