# Generated by Django 5.2.6 on 2025-09-24 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0027_alter_pricing_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetCoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.CharField(max_length=255, verbose_name='Координаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitemanagement.pet', verbose_name='Питомец')),
            ],
            options={
                'verbose_name': 'Координаты питомца',
                'verbose_name_plural': 'Координаты питомцев',
            },
        ),
    ]
