# Generated by Django 5.2.6 on 2025-09-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0028_petcoordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='tranasctions',
            name='subscription_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание подписки'),
        ),
        migrations.AddField(
            model_name='tranasctions',
            name='subscription_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало подписки'),
        ),
    ]
