# Generated by Django 5.2.6 on 2025-09-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0029_tranasctions_subscription_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
