# Generated by Django 5.2.6 on 2025-10-01 11:42

import sitemanagement.constants.image_save_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0030_alter_pricing_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('description', models.CharField(max_length=255, verbose_name='Описание продукта')),
                ('price', models.IntegerField(verbose_name='Цена продукта')),
                ('image', models.ImageField(upload_to=sitemanagement.constants.image_save_path.devices_upload_path, verbose_name='Изображение продукта')),
                ('wb_link', models.CharField(max_length=255, verbose_name='Ссылка на WB')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
                'ordering': ['id'],
            },
        ),
    ]
