# Generated by Django 5.2.6 on 2025-10-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0032_devices_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='category',
            field=models.CharField(choices=[('collars', 'Ошейники'), ('keychains', 'Брелоки')], default='collars', max_length=15, verbose_name='Категория'),
        ),
    ]
