# Generated by Django 5.2.7 on 2025-10-03 08:59

import sitemanagement.constants.image_save_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0033_devices_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonuses',
            name='imageURL',
        ),
        migrations.AddField(
            model_name='bonuses',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=sitemanagement.constants.image_save_path.bonuses_upload_path, verbose_name='Картинка для бонуса'),
        ),
    ]
