# Generated by Django 5.2.7 on 2025-10-03 09:15

import sitemanagement.constants.image_save_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0034_remove_bonuses_imageurl_bonuses_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='imageURL',
        ),
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=sitemanagement.constants.image_save_path.services_upload_path, verbose_name='Изображение продукта'),
        ),
    ]
