# Generated by Django 5.2.7 on 2025-10-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0036_alter_pet_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petcoordinates',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='petcoordinates',
            name='accuracy',
            field=models.FloatField(default=0, verbose_name='Точность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petcoordinates',
            name='latitude',
            field=models.FloatField(default=0, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petcoordinates',
            name='longitude',
            field=models.FloatField(default=0, verbose_name='Долгота'),
            preserve_default=False,
        ),
    ]
