# Generated by Django 5.2.7 on 2025-10-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0037_remove_petcoordinates_coordinates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petcoordinates',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
    ]
