# Generated by Django 5.2.7 on 2025-10-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0038_petcoordinates_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='petcoordinates',
            name='founder_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя владельца'),
        ),
        migrations.AddField(
            model_name='petcoordinates',
            name='founder_phone',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Телефон владельца'),
        ),
    ]
