# Generated by Django 5.2.7 on 2025-10-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0039_petcoordinates_founder_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tranasctions',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='tranasctions',
            name='request_id',
            field=models.CharField(default=0, max_length=255, verbose_name='ID транзакции в bePaid'),
            preserve_default=False,
        ),
    ]
