# Generated by Django 5.2.7 on 2025-10-21 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0040_remove_tranasctions_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tranasctions',
            options={'ordering': ['-id'], 'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
    ]
