# Generated by Django 5.2.7 on 2025-10-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0041_alter_tranasctions_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tranasctions',
            name='bepaid_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID транзакции в bePaid'),
        ),
        migrations.AlterField(
            model_name='tranasctions',
            name='request_id',
            field=models.CharField(max_length=255, verbose_name='Request ID в bePaid'),
        ),
    ]
