# Generated by Django 6.0 on 2025-12-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0042_tranasctions_bepaid_id_alter_tranasctions_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petcoordinates',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
