# Generated by Django 6.0 on 2025-12-12 08:31

import sitemanagement.constants.image_save_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0043_alter_petcoordinates_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpagemedia',
            name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='mainpagemedia',
            name='type',
        ),
        migrations.RemoveField(
            model_name='mainpagemedia',
            name='url',
        ),
        migrations.AddField(
            model_name='mainpagemedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=sitemanagement.constants.image_save_path.main_media_upload_path, verbose_name='Фото на главной'),
        ),
    ]
