# Generated by Django 6.0 on 2025-12-12 08:36

import sitemanagement.constants.image_save_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0044_remove_mainpagemedia_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagemedia',
            name='image',
            field=models.ImageField(upload_to=sitemanagement.constants.image_save_path.main_media_upload_path, verbose_name='Фото на главной'),
        ),
    ]
