# Generated by Django 5.2.5 on 2025-08-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('zooID', 'Зоо ID'), ('concierge', 'Зооконсьерж'), ('zoopolis', 'Зоополис')], default='zooID', max_length=20, verbose_name='Тип аккаунта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=18, unique=True, verbose_name='Номер телефона'),
        ),
    ]
