# Generated by Django 5.2.5 on 2025-08-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='privacy_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
