# Generated by Django 5.2.5 on 2025-08-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile_address_userprofile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='imageURL',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
