# Generated by Django 5.2.6 on 2025-09-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_registerqrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerqrcode',
            name='is_printed',
            field=models.BooleanField(default=False, verbose_name='Статус распечатки кода'),
        ),
    ]
