# Generated by Django 5.2.6 on 2025-09-11 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_registerqrcode_is_printed'),
        ('sitemanagement', '0027_alter_pricing_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerqrcode',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitemanagement.pet', verbose_name='Питомец'),
        ),
    ]
