# Generated by Django 5.2.6 on 2025-09-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_registerqrcode_pet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registerqrcode',
            options={'verbose_name': 'QR код', 'verbose_name_plural': 'QR коды'},
        ),
        migrations.AlterField(
            model_name='registerqrcode',
            name='is_printed',
            field=models.BooleanField(default=False, verbose_name='Распечатан'),
        ),
    ]
