# Generated by Django 5.2.6 on 2025-10-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_registerqrcode_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('zooID', 'Зоо ID'), ('concierge', 'Зооконсьерж'), ('zoopolis', 'Зоополис')], default='zooID', max_length=20, verbose_name='Тип аккаунта'),
        ),
    ]
