# Generated by Django 5.2.6 on 2025-10-01 10:46

import sitemanagement.constants.image_save_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_userprofile_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='imageURL',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=sitemanagement.constants.image_save_path.user_image_upload_path, verbose_name='Фото пользователя'),
        ),
    ]
