# Generated by Django 5.2.7 on 2025-10-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_userprofile_imageurl_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerqrcode',
            name='activation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата активации'),
        ),
    ]
