# Generated by Django 5.2.7 on 2025-10-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_registerqrcode_activation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID в Telegram'),
        ),
    ]
