# Generated by Django 5.2.7 on 2025-10-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_userprofile_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='privacy_accepted',
            field=models.BooleanField(default=False, verbose_name='Принятие политики конфиденциальности'),
        ),
    ]
