# Generated by Django 5.2.7 on 2025-10-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_userprofile_privacy_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerqrcode',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
