# Generated by Django 5.2.7 on 2025-10-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_registerqrcode_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerqrcode',
            name='verification_code',
            field=models.CharField(default=0, max_length=8, verbose_name='Код подтверждения (печатается в инструкции)'),
            preserve_default=False,
        ),
    ]
