# Generated by Django 5.2.7 on 2025-10-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_registerqrcode_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerqrcode',
            name='verification_code',
        ),
        migrations.AddField(
            model_name='registerqrcode',
            name='is_verificated',
            field=models.BooleanField(default=False, verbose_name='Статус подтверждения покупки'),
        ),
    ]
