services:
  backend:
    image: "registry.gitlab.com/wedeving/zoopolis-www/backend:{{ docker_tag }}"
    volumes:
      - "static:/static"
      - "media:/media"
    environment:
      # django settings
      ALLOWED_HOSTS: "{{domain}},backend"
      SECRET_KEY: "django-insecure-k$t@77c(qs_@+8#&#6ly(t5w=-!rc%3qluhfsl5rydq4pce@+5"
      DEBUG_MODE: true
      BASE_URL: "https://{{ domain }}"
      MEDIA_ROOT: /media
      STATIC_ROOT: /static
      CORS_ALLOW_ALL_ORIGINS: false
      CORS_ALLOWED_ORIGINS: "http://{{ domain }},https://{{ domain }},https://{{ domain_dashboard }}"
      CSRF_TRUSTED_ORIGINS: "http://{{ domain }},https://{{ domain }},https://{{ domain_dashboard }}"

      # is lost logic
      IS_LOST_URL: https://{{ domain }}/is_lost/
      REDIRECT_LOGIN_URL: https://{{ domain_dashboard }}/login

      # database
      DB_NAME: "{{ db_name }}"
      DB_USER: "{{ db_user }}"
      DB_PASSWORD: "{{ db_password }}"
      DB_HOST: postgres
      DB_PORT: 5432

      # redis
      REDIS_HOST: redis

      # email server
      CORP_EMAIL: admin@tripwb.com
      SUPPORT_EMAIL: admin@tripwb.com
      DOMAIN: tripwb.com
      PROJECT_NAME: TWB
      SENDER_MAIL_LOGIN: admin@tripwb.com
      SENDER_MAIL_PASSWORD: t5Fdcah^gdajY
      SENDER_EMAIL: admin@tripwb.com
      MAIL_SERVER_SMTP_PORT: 587
      MAIL_SERVER_URL: 213.142.147.40

      SMS_USER: info@zoopolis.org
      SMS_API_KEY: SPsIpFIV9UGwaPXuZuT7

    healthcheck:
      test: ["CMD", "sh", "-c", "ss -nltp | grep '0.0.0.0:8000'"]
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 1s

    networks:
      zoopolis:
        ipv4_address: "{{ docker_network_prefix }}.1"

    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy

  frontend:
    image: "registry.gitlab.com/wedeving/zoopolis-www/frontend:{{ docker_tag }}"
    environment:
      NEXT_PUBLIC_API_URL: https://{{ domain }}/api/v1

    networks:
      zoopolis:
        ipv4_address: "{{ docker_network_prefix }}.2"

    depends_on:
      backend:
        condition: service_healthy

  dashboard-frontend:
    image: "registry.gitlab.com/wedeving/zoopolis-www/dashboard-frontend:{{ docker_tag }}"
    environment:
      NEXT_PUBLIC_API_URL: https://{{ domain }}/api/v1
      BACKEND_URL: http://backend:8000/api/v1
      NEXTAUTH_URL: https://{{ domain_dashboard }}
      NEXTAUTH_SECRET: sdjfhshd126kbnaoTj12

      # bepaid
      CHECKOUT_URL: https://checkout.bepaid.by/ctp/api/checkouts
      PAYMENTS_TEST_MODE: false
      BEPAID_ID: 23643
      BEPAID_SECRET_KEY: e055773ef7f2c1194fd35f372665711081e48fe68df1993fe3b184182ce870bb
      BEPAID_PRIVATE_KEY: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxdu8Uij5Kh\
        A0Sn71cUkoStXkBQjsGvh7dCt4N0QcCJqVW4NrM8qnEVUAU8edhTVl17B9kHVKPiqOKSkyUMr\
        bBgaGEggyR+Pe/3ohqcZGyd+BPDsLX2AQjye7L6lv15eqDTDNM7KV81rfN1vIxWuHJt7Zjagn\
        2oOKMQbA9U0QJHn5HgLhORA+eKM49VnIyvLL4edVsNkrYqzHlpFalDCKuBc+CHZrXvJbCBO/i\
        dirNOHSFVYgAVfQtLgwwCTV0DBWdY3P/vVPiuICaQ4fxClyJzguy5TnUm1mZqsgBGOCrTEvJz\
        RKHGO+Z/DonDO/qHeeuQ4f1OnWInV7kXDStJ1NUwIDAQAB"
    networks:
      zoopolis:
        ipv4_address: "{{ docker_network_prefix }}.3"

    depends_on:
      backend:
        condition: service_healthy

  redis:
    image: redis:8-alpine
    volumes:
      - "redis:/data"
    networks:
      zoopolis:
        ipv4_address: "{{ docker_network_prefix }}.10"

  postgres:
    image: postgres:18-alpine
    volumes:
      - "postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER={{ db_user }}
      - POSTGRES_PASSWORD={{ db_password }}
      - POSTGRES_DB={{ db_name }}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      zoopolis:
        ipv4_address: "{{ docker_network_prefix }}.11"

networks:
  zoopolis:
    name: "{{ app }}_network"
    ipam:
      config:
        - subnet: "{{ docker_network_prefix }}.0/24"

volumes:
  media:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "/var/{{ app }}/media"
  static:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "/var/{{ app }}/static"
  redis:
  postgres:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "/var/{{ app }}/postgres"
