image := "dashboard-frontend"

import "../docker.just"

docker-prod: docker-build-internal Dockerfile.prod prod
docker-stage: docker-build-internal Dockerfile.stage stage
push-prod: docker-push-internal prod
push-stage: docker-push-internal stage
