image := "backend"

import "../docker.just"

docker-prod: docker-build-internal Dockerfile prod
docker-stage: docker-build-internal Dockerfile stage
push-prod: docker-push-internal prod
push-stage: docker-push-internal stage
