servers:
  hosts:
    zoopolis:
      ansible_host: zoopolis.org

  vars:
    ansible_user: root

    app: zoopolis

    user: zoo
    timezone: Europe/Minsk
    ssh_keys: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP+igmEmZ9KzELTgYKLrW/LcFIclzj0m2enPp5Bm4QSz promo@vhome6
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFIOJE+HAkS+l7kDMNsQAMsVxdBoKn6UKg1NwO/KJ5I+ timofey.syr17@gmail.com

    db_user: admin
    db_password: eequeiTh0Yeiwoo4Ahra
    db_name: zoopolisdb

    registry_user: gitlab+deploy-token-9189607
    registry_token: gldt-15QsUAVXE8SR-W3rAziA

    domain: stage.zoopolis.org
    domain_dashboard: stage.account.zoopolis.org
    enable_https: true

    http_user: zoopolis
    http_pass: welcome
    http_auth: false
