import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css";
import Header from "@/components/Header"
import Footer from "@/components/Footer"
import { Toaster } from 'react-hot-toast'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Zoopolis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col font-dispay">
  
          <Header />
          <main className="flex-grow">{children}</main>
          <Toaster />
          <Footer />
     
      </body>
    </html>
  );
}
