import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header"
import Footer from "@/components/Footer"
import { Toaster } from 'react-hot-toast'

export const metadata: Metadata = {
  title: "Zoopolis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col font-dispay">
  
          <Header />
          <main className="flex-grow">{children}</main>
          <Toaster />
          <Footer />
     
      </body>
    </html>
  );
}
