# Generated by Django 5.2.5 on 2025-08-19 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetsColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название цвета')),
                ('hex_code', models.CharField(max_length=255, verbose_name='HEX код цвета')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Цвет питомца',
                'verbose_name_plural': 'Цвета питомцев',
            },
        ),
        migrations.CreateModel(
            name='PetsTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название типа питомца')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Тип питомца',
                'verbose_name_plural': 'Типы питомцев',
            },
        ),
        migrations.CreateModel(
            name='PetsBreeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название породы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('pet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionaries.petstypes', verbose_name='Тип питомца')),
            ],
            options={
                'verbose_name': 'Порода питомца',
                'verbose_name_plural': 'Породы питомцев',
            },
        ),
    ]
