- name: Postgresql config
  hosts: servers
  tasks:
    - name: Key dir
      ansible.builtin.file:
        path: "/usr/share/postgresql-common/pgdg"
        state: directory
        mode: "0755"

    - name: Add apt key
      ansible.builtin.get_url:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        dest: /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc
        mode: "0644"

    - name: Add postgresql repo
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] \
               https://apt.postgresql.org/pub/repos/apt {{ ansible_facts['distribution_release'] }}-pgdg main"
        state: present

    - name: Preinstall packages
      ansible.builtin.package:
        name:
          - postgresql-client-18
          - python3-psycopg2

    - name: App data dir
      ansible.builtin.file:
        path: "/var/{{ app }}"
        state: directory
        mode: "0755"

    - name: Postgres dir
      ansible.builtin.file:
        path: "/var/{{ app }}/postgres"
        state: directory
        mode: "0755"

    - name: Docker compose project dir
      ansible.builtin.file:
        path: "/etc/docker/compose/{{ app }}-pg"
        state: directory
        mode: "0755"

    - name: Docker compose file
      ansible.builtin.template:
        src: "pgconfig/pg-compose.yml"
        dest: "/etc/docker/compose/{{ app }}-pg/docker-compose.yml"
        mode: "0644"
      notify: Restart compose service

    - name: Systemd service
      ansible.builtin.systemd:
        name: "compose@{{ app }}-pg"
        state: started
        daemon_reload: true
        enabled: true

    - name: Create db user
      community.postgresql.postgresql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        login_host: "{{ docker_network_prefix }}.30"
        login_user: "{{ db_admin_user }}"
        login_password: "{{ db_admin_password }}"
        login_db: "{{ db_admin_name }}"

    - name: Create database
      community.postgresql.postgresql_db:
        name: "{{ db_name }}"
        owner: "{{ db_user }}"
        login_host: "{{ docker_network_prefix }}.30"
        login_user: "{{ db_admin_user }}"
        login_password: "{{ db_admin_password }}"

    - name: Pgpass
      ansible.builtin.lineinfile:
        path: "/home/{{ user }}/.pgpass"
        line: "pg-{{ app }}:5432:{{ db_name }}:{{ db_user }}:{{ db_password }}"
        create: true
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0600"

    - name: Host
      ansible.builtin.lineinfile:
        path: /etc/hosts
        state: present
        search_string: "{{ docker_network_prefix }}.30"
        line: "{{ docker_network_prefix }}.30 pg-{{ app }}"

  handlers:
    - name: Restart compose service
      ansible.builtin.service:
        name: "compose@{{ app }}-pg"
        state: restarted
