- name: Redis
  hosts: servers
  tasks:
    - name: Install packages
      ansible.builtin.package:
        name:
          - redis

    - name: Set redis listen addresses
      ansible.builtin.lineinfile:
        path: /etc/redis/redis.conf
        regexp: "^bind"
        line: "bind 127.0.0.1 172.56.0.1"
      notify: Restart redis

  handlers:
    - name: Restart redis
      ansible.builtin.service:
        name: redis
        state: restarted
