import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/Header'
import { Toaster } from 'react-hot-toast'
import { Providers } from './providers/Providers'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-display flex min-h-screen flex-col">
        <Providers>
          <Header />
          <main className="flex-grow">{children}</main>
          <Toaster />
        </Providers>
      </body>
    </html>
  )
}
